services:
    keycloak-srv:
      image: quay.io/keycloak/keycloak:latest
      command: ["start-dev", "--http-port=8180", "--import-realm"]
      ports:
        - 8180:8180
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin123
        #KEYCLOAK_IMPORT: /opt/keycloak/data/imports/onlineshop-dev-realm.json
      volumes:
        - ./keycloak:/opt/keycloak/data/import
        # - type: volume
        #   source: keycloak-volume
        #   target: /opt/keycloak/data
        # - type: bind
        #   source: ./keycloak/onlineshop-dev-realm.json
        #   target: /tmp/onlineshop-dev-realm.json

    online-shop-angular:
      container_name: online-shop-angular
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 4200:4200
      develop:
        watch:
          - path: ./package.json
            action: rebuild
          - path: ./
            target: /usr/src/app
            action: sync
